#:schema node_modules/wrangler/config-schema.json
name = "airdrop-backend"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

routes = [{ pattern = "airdrop-api.yankeguo.com", custom_domain = true }]

[[d1_databases]]
binding = "DB_AIRDROP"
database_name = "airdrop"
database_id = "ddab7526-392a-43f8-b890-05111d472b8a"
